// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maket12/ads-service/backend/searchservice/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockAdIndexRepository is an autogenerated mock type for the AdIndexRepository type
type MockAdIndexRepository struct {
	mock.Mock
}

type MockAdIndexRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdIndexRepository) EXPECT() *MockAdIndexRepository_Expecter {
	return &MockAdIndexRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAdIndexRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdIndexRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAdIndexRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAdIndexRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAdIndexRepository_Delete_Call {
	return &MockAdIndexRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAdIndexRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockAdIndexRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdIndexRepository_Delete_Call) Return(_a0 error) *MockAdIndexRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdIndexRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockAdIndexRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function with given fields: ctx, adIndex
func (_m *MockAdIndexRepository) Index(ctx context.Context, adIndex *model.AdIndex) error {
	ret := _m.Called(ctx, adIndex)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdIndex) error); ok {
		r0 = rf(ctx, adIndex)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdIndexRepository_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockAdIndexRepository_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx context.Context
//   - adIndex *model.AdIndex
func (_e *MockAdIndexRepository_Expecter) Index(ctx interface{}, adIndex interface{}) *MockAdIndexRepository_Index_Call {
	return &MockAdIndexRepository_Index_Call{Call: _e.mock.On("Index", ctx, adIndex)}
}

func (_c *MockAdIndexRepository_Index_Call) Run(run func(ctx context.Context, adIndex *model.AdIndex)) *MockAdIndexRepository_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.AdIndex))
	})
	return _c
}

func (_c *MockAdIndexRepository_Index_Call) Return(_a0 error) *MockAdIndexRepository_Index_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdIndexRepository_Index_Call) RunAndReturn(run func(context.Context, *model.AdIndex) error) *MockAdIndexRepository_Index_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, query
func (_m *MockAdIndexRepository) Search(ctx context.Context, query *model.SearchQuery) ([]*model.AdIndex, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*model.AdIndex
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SearchQuery) ([]*model.AdIndex, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.SearchQuery) []*model.AdIndex); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AdIndex)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.SearchQuery) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.SearchQuery) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAdIndexRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockAdIndexRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query *model.SearchQuery
func (_e *MockAdIndexRepository_Expecter) Search(ctx interface{}, query interface{}) *MockAdIndexRepository_Search_Call {
	return &MockAdIndexRepository_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockAdIndexRepository_Search_Call) Run(run func(ctx context.Context, query *model.SearchQuery)) *MockAdIndexRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SearchQuery))
	})
	return _c
}

func (_c *MockAdIndexRepository_Search_Call) Return(_a0 []*model.AdIndex, _a1 int64, _a2 error) *MockAdIndexRepository_Search_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAdIndexRepository_Search_Call) RunAndReturn(run func(context.Context, *model.SearchQuery) ([]*model.AdIndex, int64, error)) *MockAdIndexRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdIndexRepository creates a new instance of MockAdIndexRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdIndexRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdIndexRepository {
	mock := &MockAdIndexRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
