version: "2"

run:
  timeout: 5m
  tests: true

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
  staticcheck:
    checks:
      - "all"
      - "-ST1000"
      - "-ST1003"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
  settings:
    staticcheck:
      checks:
        - all

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true