""" User Role """
enum UserRole {
    user
    admin
}

""" User (Account + Role + Profile) """
type User {
    id: ID!
    role: UserRole!
    firstName: String
    lastName: String
    phone: String
    avatarUrl: String
    bio: String
    updatedAt: String
}

""" Login Response """
type LoginResponse {
    accessToken: String!
    refreshToken: String!
}

""" Refresh Session Response """
type RefreshSessionResponse {
    accessToken: String!
    refreshToken: String!
}

""" Validate Access Token Response """
type ValidateAccessTokenResponse {
    accountId: ID!
    role: UserRole!
}

""" Ad Status"""
enum AdStatus {
    on_moderation
    published
    rejected
    deleted
}

""" Ad - full info """
type Ad {
    id: ID!
    sellerId: ID!
    title: String!
    description: String
    price: Float!
    status: AdStatus!
    images: [String!]
    createdAt: String!
    updatedAt: String
}

# ---- Inputs ----

input RegisterInput {
    email: String!
    password: String!
}

input LoginInput {
    email: String!
    password: String!
    ip: String
    userAgent: String
}

input RefreshSessionInput {
    oldRefreshToken: String!
    ip: String
    userAgent: String
}

input UpdateProfileInput {
    firstName: String
    lastName: String
    phone: String
    avatarUrl: String
    bio: String
}

input CreateAdInput {
    title: String!
    description: String
    price: Float!
    images: [String!]
}

input UpdateAdInput {
    adId: ID!
    title: String
    description: String
    price: Float
    images: [String!]
}

type Query {
    # rpc GetProfile
    me: User

    # rpc GetAd
    ad(adId: ID!): Ad

    # rpc ListAds
    ads: [Ad!]!

    # rpc ListAllAds
    allAds(limit: Int!, offset: Int!): [Ad!]!

    # rpc ValidateAccessToken
    validateAccessToken(token: String!): ValidateAccessTokenResponse!
}

type Mutation {
    # --- Auth Service methods ---

    # rpc Register
    register(input: RegisterInput!): ID!

    # rpc Login
    login(input: LoginInput!): LoginResponse!

    # rpc Logout
    logout(refreshToken: String!): Boolean!

    # rpc RefreshSession
    refreshSession(input: RefreshSessionInput!): RefreshSessionResponse!

    # rpc AssignRole
    assignRole(accountId: ID!, role: UserRole!): Boolean!

    # rpc SendVerification
    sendVerification(accountId: ID!): Boolean!

    # rpc VerifyEmail
    verifyEmail(token: String!): Boolean!

    # rpc BlockAccount
    block(accountId: ID!): Boolean!

    # rpc DeleteAccount
    delete(accountId: ID!): Boolean!


    # --- User Service methods ---

    # rpc UpdateProfile
    updateProfile(input: UpdateProfileInput!): Boolean!

    # --- Ad Service methods ---

    # rpc CreateAd
    createAd(input: CreateAdInput!): ID!

    # rpc UpdateAd
    updateAd(input: UpdateAdInput!): Boolean!

    # rpc PublishAd
    publish(adId: ID!): Boolean!

    # rpc RejectAd
    reject(adId: ID!): Boolean!

    # rpc DeleteAd
    deleteAd(adId: ID!): Boolean!

    # rpc DeleteAllAds
    deleteAllAds(sellerId: ID!): Boolean!
}
