package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/maket12/ads-service/backend/adservice/pkg/generated/ad_v1"
	"github.com/maket12/ads-service/backend/authservice/api/proto/generated/auth_v1"
	authutils "github.com/maket12/ads-service/backend/authservice/pkg/utils"
	"github.com/maket12/ads-service/backend/gateway/graph/model"
	"github.com/maket12/ads-service/backend/userservice/api/proto/generated/user_v1"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

var (
	RoleUser  = "user"
	RoleAdmin = "admin"
)

func requireAuth(ctx context.Context) (string, error) {
	accountID, ok := authutils.GetAccountIDFromCtx(ctx)
	if !ok || accountID == "" {
		return "", &gqlerror.Error{
			Message:    "authentication required",
			Extensions: map[string]interface{}{"code": "UNAUTHENTICATED"},
		}
	}
	return accountID, nil
}
func requireRole(ctx context.Context, role string) (string, error) {
	accountID, err := requireAuth(ctx)
	if err != nil {
		return "", err
	}
	actualRole := authutils.GetAccountRoleFromCtx(ctx)
	if actualRole != role {
		return "", &gqlerror.Error{
			Message:    "forbidden",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		}
	}
	return accountID, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (string, error) {
	resp, err := r.AuthClient.Register(ctx, &auth_v1.RegisterRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return "", mapGRPCError(err)
	}
	return resp.AccountId, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginResponse, error) {
	resp, err := r.AuthClient.Login(ctx, &auth_v1.LoginRequest{
		Email:     input.Email,
		Password:  input.Password,
		Ip:        input.IP,
		UserAgent: input.UserAgent,
	})
	if err != nil {
		return nil, mapGRPCError(err)
	}

	return &model.LoginResponse{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken string) (bool, error) {
	resp, err := r.AuthClient.Logout(ctx, &auth_v1.LogoutRequest{
		RefreshToken: refreshToken,
	})
	if err != nil {
		return false, mapGRPCError(err)
	}
	return resp.Logout, nil
}

// RefreshSession is the resolver for the refreshSession field.
func (r *mutationResolver) RefreshSession(ctx context.Context, input model.RefreshSessionInput) (*model.RefreshSessionResponse, error) {
	resp, err := r.AuthClient.RefreshSession(ctx, &auth_v1.RefreshSessionRequest{
		OldRefreshToken: input.OldRefreshToken,
		Ip:              input.IP,
		UserAgent:       input.UserAgent,
	})
	if err != nil {
		return nil, mapGRPCError(err)
	}

	return &model.RefreshSessionResponse{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
	}, nil
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, accountID string, role model.UserRole) (bool, error) {
	if _, err := requireRole(ctx, RoleAdmin); err != nil {
		return false, err
	}

	resp, err := r.AuthClient.AssignRole(ctx, &auth_v1.AssignRoleRequest{
		AccountId: accountID,
		Role:      role.String(),
	})
	if err != nil {
		return false, mapGRPCError(err)
	}

	return resp.Assigned, nil
}

// SendVerification is the resolver for the sendVerification field.
func (r *mutationResolver) SendVerification(ctx context.Context, accountID string) (bool, error) {
	resp, err := r.AuthClient.SendVerification(ctx, &auth_v1.SendVerificationRequest{
		AccountId: accountID,
	})
	if err != nil {
		return false, mapGRPCError(err)
	}
	return resp.Sent, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (bool, error) {
	resp, err := r.AuthClient.VerifyEmail(ctx, &auth_v1.VerifyEmailRequest{Token: token})
	if err != nil {
		return false, mapGRPCError(err)
	}
	return resp.Verified, nil
}

// Block is the resolver for the block field.
func (r *mutationResolver) Block(ctx context.Context, accountID string) (bool, error) {
	if _, err := requireRole(ctx, RoleAdmin); err != nil {
		return false, err
	}

	resp, err := r.AuthClient.BlockAccount(ctx, &auth_v1.BlockAccountRequest{
		AccountId: accountID,
	})
	if err != nil {
		return false, mapGRPCError(err)
	}

	return resp.Blocked, nil
}

// Delete is the resolver for the delete field.
func (r *mutationResolver) Delete(ctx context.Context, accountID string) (bool, error) {
	if _, err := requireRole(ctx, RoleAdmin); err != nil {
		return false, err
	}

	resp, err := r.AuthClient.DeleteAccount(ctx, &auth_v1.DeleteAccountRequest{
		AccountId: accountID,
	})
	if err != nil {
		return false, mapGRPCError(err)
	}

	return resp.Deleted, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}

	resp, err := r.UserClient.UpdateProfile(ctx, &user_v1.UpdateProfileRequest{
		FirstName: input.FirstName,
		LastName:  input.LastName,
		Phone:     input.Phone,
		AvatarUrl: input.AvatarURL,
		Bio:       input.Bio,
	})
	if err != nil {
		return false, mapGRPCError(err)
	}

	return resp.Success, nil
}

// CreateAd is the resolver for the createAd field.
func (r *mutationResolver) CreateAd(ctx context.Context, input model.CreateAdInput) (string, error) {
	if _, err := requireAuth(ctx); err != nil {
		return "", err
	}

	resp, err := r.AdClient.CreateAd(ctx, &ad_v1.CreateAdRequest{
		Title:       input.Title,
		Description: input.Description,
		Price:       int64(input.Price),
		Category:    input.Category,
		Images:      input.Images,
	})
	if err != nil {
		return "", mapGRPCError(err)
	}

	return resp.Id, nil
}

// UpdateAd is the resolver for the updateAd field.
func (r *mutationResolver) UpdateAd(ctx context.Context, input model.UpdateAdInput) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}

	resp, err := r.AdClient.UpdateAd(ctx, &ad_v1.UpdateAdRequest{
		Id:          input.AdID,
		Title:       input.Title,
		Description: input.Description,
		Price:       mapFloatPtrToInt(input.Price),
		Category:    input.Category,
		Images:      input.Images,
	})
	if err != nil {
		return false, mapGRPCError(err)
	}

	return resp.Success, nil
}

// Publish is the resolver for the publish field.
func (r *mutationResolver) Publish(ctx context.Context, adID string) (bool, error) {
	if _, err := requireRole(ctx, RoleAdmin); err != nil {
		return false, err
	}

	resp, err := r.AdClient.PublishAd(ctx, &ad_v1.PublishAdRequest{Id: adID})
	if err != nil {
		return false, mapGRPCError(err)
	}

	return resp.Success, nil
}

// Reject is the resolver for the reject field.
func (r *mutationResolver) Reject(ctx context.Context, adID string) (bool, error) {
	if _, err := requireRole(ctx, RoleAdmin); err != nil {
		return false, err
	}

	resp, err := r.AdClient.RejectAd(ctx, &ad_v1.RejectAdRequest{Id: adID})
	if err != nil {
		return false, mapGRPCError(err)
	}

	return resp.Success, nil
}

// DeleteAd is the resolver for the deleteAd field.
func (r *mutationResolver) DeleteAd(ctx context.Context, adID string) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}

	resp, err := r.AdClient.DeleteAd(ctx, &ad_v1.DeleteAdRequest{Id: adID})
	if err != nil {
		return false, mapGRPCError(err)
	}

	return resp.Success, nil
}

// DeleteAllAds is the resolver for the deleteAllAds field.
func (r *mutationResolver) DeleteAllAds(ctx context.Context, sellerID string) (bool, error) {
	if _, err := requireRole(ctx, RoleAdmin); err != nil {
		return false, err
	}

	resp, err := r.AdClient.DeleteAllAds(ctx, &ad_v1.DeleteAllAdsRequest{
		SellerId: sellerID,
	})
	if err != nil {
		return false, mapGRPCError(err)
	}

	return resp.Success, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	accountID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	role := model.UserRole(authutils.GetAccountRoleFromCtx(ctx))

	resp, err := r.UserClient.GetProfile(ctx, &user_v1.GetProfileRequest{})
	if err != nil {
		return nil, mapGRPCError(err)
	}

	return &model.User{
		ID:        accountID,
		Role:      role,
		FirstName: resp.FirstName,
		LastName:  resp.LastName,
		Phone:     resp.Phone,
		AvatarURL: resp.AvatarUrl,
		Bio:       resp.Bio,
		UpdatedAt: authutils.VPtr(resp.UpdatedAt.String()),
	}, nil
}

// Ad is the resolver for the ad field.
func (r *queryResolver) Ad(ctx context.Context, adID string) (*model.Ad, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	resp, err := r.AdClient.GetAd(ctx, &ad_v1.GetAdRequest{Id: adID})
	if err != nil {
		return nil, mapGRPCError(err)
	}

	return mapAdGRPCToGateway(resp.Ad), nil
}

// Ads is the resolver for the ads field.
func (r *queryResolver) Ads(ctx context.Context) ([]*model.Ad, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	resp, err := r.AdClient.ListAds(ctx, &ad_v1.ListAdsRequest{})
	if err != nil {
		return nil, mapGRPCError(err)
	}

	return mapAdListGRPCToGateway(resp.Ads), nil
}

// AllAds is the resolver for the allAds field.
func (r *queryResolver) AllAds(ctx context.Context, limit int, offset int) ([]*model.Ad, error) {
	if _, err := requireRole(ctx, RoleAdmin); err != nil {
		return nil, err
	}

	resp, err := r.AdClient.ListAllAds(ctx, &ad_v1.ListAllAdsRequest{
		Limit:  int32(limit),
		Offset: int32(offset),
	})
	if err != nil {
		return nil, mapGRPCError(err)
	}

	return mapAdListGRPCToGateway(resp.Ads), nil
}

// ValidateAccessToken is the resolver for the validateAccessToken field.
func (r *queryResolver) ValidateAccessToken(ctx context.Context, token string) (*model.ValidateAccessTokenResponse, error) {
	resp, err := r.AuthClient.ValidateAccessToken(ctx, &auth_v1.ValidateAccessTokenRequest{
		AccessToken: token,
	})
	if err != nil {
		return nil, mapGRPCError(err)
	}
	return &model.ValidateAccessTokenResponse{
		AccountID: resp.AccountId,
		Role:      model.UserRole(resp.Role),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
