package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/maket12/ads-service/backend/adservice/pkg/generated/ad_v1"
	"github.com/maket12/ads-service/backend/authservice/pkg/generated/auth_v1"
	"github.com/maket12/ads-service/backend/authservice/pkg/utils"
	"github.com/maket12/ads-service/backend/gateway/graph/model"
	"github.com/maket12/ads-service/backend/userservice/pkg/generated/user_v1"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (string, error) {
	resp, err := r.AuthClient.Register(ctx, &auth_v1.RegisterRequest{
		Email:    email,
		Password: password,
	})
	if err != nil {
		return "", err
	}
	return resp.GetAccountId(), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginResponse, error) {
	resp, err := r.AuthClient.Login(ctx, &auth_v1.LoginRequest{
		Email:     email,
		Password:  password,
		Ip:        ip,
		UserAgent: userAgent,
	})
	if err != nil {
		return nil, err
	}
	return &auth_v1.LoginResponse{
		AccessToken:  resp.GetAccessToken(),
		RefreshToken: resp.GetRefreshToken(),
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken string) (bool, error) {
	resp, err := r.AuthClient.Logout(
		ctx, &auth_v1.LogoutRequest{RefreshToken: refreshToken},
	)
	if err != nil {
		return false, err
	}
	return resp.GetLogout(), nil
}

// RefreshSession is the resolver for the refreshSession field.
func (r *mutationResolver) RefreshSession(ctx context.Context, input model.RefreshSessionInput) (*model.RefreshSessionResponse, error) {
	resp, err := r.AuthClient.RefreshSession(ctx, &auth_v1.RefreshSessionRequest{
		OldRefreshToken: oldRefreshToken,
		Ip:              ip,
		UserAgent:       userAgent,
	})
	if err != nil {
		return nil, err
	}
	return &auth_v1.RefreshSessionResponse{
		AccessToken:  resp.GetAccessToken(),
		RefreshToken: resp.GetRefreshToken(),
	}, nil
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, accountID string, role model.UserRole) (bool, error) {
	resp, err := r.AuthClient.AssignRole(ctx, &auth_v1.AssignRoleRequest{
		AccountId: accountID,
		Role:      role,
	})
	if err != nil {
		return false, err
	}
	return resp.GetAssign(), nil
}

// SendVerification is the resolver for the sendVerification field.
func (r *mutationResolver) SendVerification(ctx context.Context, accountID string) (bool, error) {
	panic(fmt.Errorf("not implemented: SendVerification - sendVerification"))
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (bool, error) {
	panic(fmt.Errorf("not implemented: VerifyEmail - verifyEmail"))
}

// Block is the resolver for the block field.
func (r *mutationResolver) Block(ctx context.Context, accountID string) (bool, error) {
	panic(fmt.Errorf("not implemented: Block - block"))
}

// Delete is the resolver for the delete field.
func (r *mutationResolver) Delete(ctx context.Context, accountID string) (bool, error) {
	panic(fmt.Errorf("not implemented: Delete - delete"))
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (bool, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return false, fmt.Errorf("unauthorized")
	}

	outCtx := utils.PackAccountIDForGRPC(ctx, idVal.(string))

	resp, err := r.UserClient.UpdateProfile(outCtx, &user_v1.UpdateProfileRequest{
		FirstName: firstName,
		LastName:  lastName,
		Phone:     phone,
		AvatarUrl: avatarURL,
		Bio:       bio,
	})
	if err != nil {
		return false, err
	}

	return resp.GetSuccess(), nil
}

// CreateAd is the resolver for the createAd field.
func (r *mutationResolver) CreateAd(ctx context.Context, input model.CreateAdInput) (string, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return "", fmt.Errorf("unauthorized")
	}

	outCtx := utils.PackAccountIDForGRPC(ctx, idVal.(string))

	var imagesFixed []string
	if len(images) != 0 {
		for i := range images {
			if images[i] != nil {
				imagesFixed[i] = *images[i]
			}
		}
	}

	resp, err := r.AdClient.CreateAd(outCtx, &ad_v1.CreateAdRequest{
		Title:       title,
		Description: description,
		Price:       int64(price),
		Images:      imagesFixed,
	})
	if err != nil {
		return "", err
	}

	return resp.GetAdId(), nil
}

// UpdateAd is the resolver for the updateAd field.
func (r *mutationResolver) UpdateAd(ctx context.Context, input model.UpdateAdInput) (bool, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return false, fmt.Errorf("unauthorized")
	}

	outCtx := utils.PackAccountIDForGRPC(ctx, idVal.(string))

	var priceFixed int64
	if price != nil {
		priceFixed = int64(*price)
	}

	var imagesFixed []string
	if len(images) != 0 {
		for i := range images {
			if images[i] != nil {
				imagesFixed[i] = *images[i]
			}
		}
	}

	resp, err := r.AdClient.UpdateAd(outCtx, &ad_v1.UpdateAdRequest{
		AdId:        adID,
		Title:       title,
		Description: description,
		Price:       &priceFixed,
		Images:      imagesFixed,
	})
	if err != nil {
		return false, err
	}

	return resp.GetSuccess(), nil
}

// Publish is the resolver for the publish field.
func (r *mutationResolver) Publish(ctx context.Context, adID string) (bool, error) {
	panic(fmt.Errorf("not implemented: Publish - publish"))
}

// Reject is the resolver for the reject field.
func (r *mutationResolver) Reject(ctx context.Context, adID string) (bool, error) {
	panic(fmt.Errorf("not implemented: Reject - reject"))
}

// DeleteAd is the resolver for the deleteAd field.
func (r *mutationResolver) DeleteAd(ctx context.Context, adID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAd - deleteAd"))
}

// DeleteAllAds is the resolver for the deleteAllAds field.
func (r *mutationResolver) DeleteAllAds(ctx context.Context, sellerID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAllAds - deleteAllAds"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	roleVal := ctx.Value(utils.AccountRoleKey)
	if roleVal == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	outCtx := utils.PackAccountIDForGRPC(ctx, idVal.(string))
	outCtx = utils.PackAccountRoleForGRPC(outCtx, roleVal.(string))

	return r.UserClient.GetProfile(outCtx, &user_v1.GetProfileRequest{})
}

// Ad is the resolver for the ad field.
func (r *queryResolver) Ad(ctx context.Context, adID string) (*model.Ad, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	outCtx := utils.PackAccountIDForGRPC(ctx, idVal.(string))

	return r.AdClient.GetAd(outCtx, &ad_v1.GetAdRequest{AdId: adID})
}

// Ads is the resolver for the ads field.
func (r *queryResolver) Ads(ctx context.Context) ([]*model.Ad, error) {
	panic(fmt.Errorf("not implemented: Ads - ads"))
}

// AllAds is the resolver for the allAds field.
func (r *queryResolver) AllAds(ctx context.Context, limit int, offset int) ([]*model.Ad, error) {
	panic(fmt.Errorf("not implemented: AllAds - allAds"))
}

// ValidateAccessToken is the resolver for the validateAccessToken field.
func (r *queryResolver) ValidateAccessToken(ctx context.Context, token string) (*model.ValidateAccessTokenResponse, error) {
	panic(fmt.Errorf("not implemented: ValidateAccessToken - validateAccessToken"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
