package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/maket12/ads-service/backend/authservice/pkg/generated/auth_v1"
	authutils "github.com/maket12/ads-service/backend/authservice/pkg/utils"
	"github.com/maket12/ads-service/backend/gateway/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

var (
	RoleUser  = "USER"
	RoleAdmin = "ADMIN"
)

func requireAuth(ctx context.Context) (string, error) {
	accountID, ok := authutils.GetAccountIDFromCtx(ctx)
	if !ok || accountID == "" {
		return "", &gqlerror.Error{
			Message:    "authentication required",
			Extensions: map[string]interface{}{"code": "UNAUTHENTICATED"},
		}
	}
	return accountID, nil
}

func requireRole(ctx context.Context, role string) (string, error) {
	accountID, err := requireAuth(ctx)
	if err != nil {
		return "", err
	}
	actualRole := authutils.GetAccountRoleFromCtx(ctx)
	if actualRole != role {
		return "", &gqlerror.Error{
			Message:    "forbidden",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		}
	}
	return accountID, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (string, error) {
	resp, err := r.AuthClient.Register(ctx, &auth_v1.RegisterRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return "", mapGRPCError(err)
	}
	return resp.AccountId, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginResponse, error) {
	resp, err := r.AuthClient.Login(ctx, &auth_v1.LoginRequest{
		Email:     input.Email,
		Password:  input.Password,
		Ip:        input.IP,
		UserAgent: input.UserAgent,
	})
	if err != nil {
		return nil, mapGRPCError(err)
	}

	return &model.LoginResponse{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken string) (bool, error) {
	resp, err := r.AuthClient.Logout(ctx, &auth_v1.LogoutRequest{
		RefreshToken: refreshToken,
	})
	if err != nil {
		return false, mapGRPCError(err)
	}
	return resp.Logout, nil
}

// RefreshSession is the resolver for the refreshSession field.
func (r *mutationResolver) RefreshSession(ctx context.Context, input model.RefreshSessionInput) (*model.RefreshSessionResponse, error) {
	resp, err := r.AuthClient.RefreshSession(ctx, &auth_v1.RefreshSessionRequest{
		OldRefreshToken: input.OldRefreshToken,
		Ip:              input.IP,
		UserAgent:       input.UserAgent,
	})
	if err != nil {
		return nil, mapGRPCError(err)
	}

	return &model.RefreshSessionResponse{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
	}, nil
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, accountID string, role model.UserRole) (bool, error) {
	if _, err := requireRole(ctx, RoleAdmin); err != nil {
		return false, err
	}

	resp, err := r.AuthClient.AssignRole(ctx, &auth_v1.AssignRoleRequest{
		AccountId: accountID,
		Role:      role.String(),
	})
	if err != nil {
		return false, mapGRPCError(err)
	}

	return resp.Assigned, nil
}

// SendVerification is the resolver for the sendVerification field.
func (r *mutationResolver) SendVerification(ctx context.Context, accountID string) (bool, error) {
	resp, err := r.AuthClient.SendVerification(ctx, &auth_v1.SendVerificationRequest{
		AccountId: accountID,
	})
	if err != nil {
		return false, mapGRPCError(err)
	}
	return resp.Sent, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (bool, error) {
	resp, err := r.AuthClient.VerifyEmail(ctx, &auth_v1.VerifyEmailRequest{Token: token})
	if err != nil {
		return false, mapGRPCError(err)
	}
	return resp.Verified, nil
}

// Block is the resolver for the block field.
func (r *mutationResolver) Block(ctx context.Context, accountID string) (bool, error) {
	if _, err := requireRole(ctx, RoleAdmin); err != nil {
		return false, err
	}

	resp, err := r.AuthClient.BlockAccount(ctx, &auth_v1.BlockAccountRequest{
		AccountId: accountID,
	})
	if err != nil {
		return false, mapGRPCError(err)
	}

	return resp.Blocked, nil
}

// Delete is the resolver for the delete field.
func (r *mutationResolver) Delete(ctx context.Context, accountID string) (bool, error) {
	panic(fmt.Errorf("not implemented: Delete - delete"))
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (bool, error) {
	panic(fmt.Errorf("not implemented: UpdateProfile - updateProfile"))
}

// CreateAd is the resolver for the createAd field.
func (r *mutationResolver) CreateAd(ctx context.Context, input model.CreateAdInput) (string, error) {
	panic(fmt.Errorf("not implemented: CreateAd - createAd"))
}

// UpdateAd is the resolver for the updateAd field.
func (r *mutationResolver) UpdateAd(ctx context.Context, input model.UpdateAdInput) (bool, error) {
	panic(fmt.Errorf("not implemented: UpdateAd - updateAd"))
}

// Publish is the resolver for the publish field.
func (r *mutationResolver) Publish(ctx context.Context, adID string) (bool, error) {
	panic(fmt.Errorf("not implemented: Publish - publish"))
}

// Reject is the resolver for the reject field.
func (r *mutationResolver) Reject(ctx context.Context, adID string) (bool, error) {
	panic(fmt.Errorf("not implemented: Reject - reject"))
}

// DeleteAd is the resolver for the deleteAd field.
func (r *mutationResolver) DeleteAd(ctx context.Context, adID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAd - deleteAd"))
}

// DeleteAllAds is the resolver for the deleteAllAds field.
func (r *mutationResolver) DeleteAllAds(ctx context.Context, sellerID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAllAds - deleteAllAds"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Ad is the resolver for the ad field.
func (r *queryResolver) Ad(ctx context.Context, adID string) (*model.Ad, error) {
	panic(fmt.Errorf("not implemented: Ad - ad"))
}

// Ads is the resolver for the ads field.
func (r *queryResolver) Ads(ctx context.Context) ([]*model.Ad, error) {
	panic(fmt.Errorf("not implemented: Ads - ads"))
}

// AllAds is the resolver for the allAds field.
func (r *queryResolver) AllAds(ctx context.Context, limit int, offset int) ([]*model.Ad, error) {
	panic(fmt.Errorf("not implemented: AllAds - allAds"))
}

// ValidateAccessToken is the resolver for the validateAccessToken field.
func (r *queryResolver) ValidateAccessToken(ctx context.Context, token string) (*model.ValidateAccessTokenResponse, error) {
	panic(fmt.Errorf("not implemented: ValidateAccessToken - validateAccessToken"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
