// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/maket12/ads-service/authservice/internal/app/dto"
	mock "github.com/stretchr/testify/mock"
)

// AssignRoleUseCase is an autogenerated mock type for the AssignRoleUseCase type
type AssignRoleUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, in
func (_m *AssignRoleUseCase) Execute(ctx context.Context, in dto.AssignRoleInput) (dto.AssignRoleOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.AssignRoleOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.AssignRoleInput) (dto.AssignRoleOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.AssignRoleInput) dto.AssignRoleOutput); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.AssignRoleOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.AssignRoleInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAssignRoleUseCase creates a new instance of AssignRoleUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssignRoleUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssignRoleUseCase {
	mock := &AssignRoleUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
