// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/maket12/ads-service/authservice/internal/app/dto"
	mock "github.com/stretchr/testify/mock"
)

// RefreshSessionUseCase is an autogenerated mock type for the RefreshSessionUseCase type
type RefreshSessionUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, in
func (_m *RefreshSessionUseCase) Execute(ctx context.Context, in dto.RefreshSessionInput) (dto.RefreshSessionOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.RefreshSessionOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RefreshSessionInput) (dto.RefreshSessionOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RefreshSessionInput) dto.RefreshSessionOutput); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.RefreshSessionOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RefreshSessionInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRefreshSessionUseCase creates a new instance of RefreshSessionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshSessionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshSessionUseCase {
	mock := &RefreshSessionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
