// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/maket12/ads-service/authservice/internal/app/dto"
	mock "github.com/stretchr/testify/mock"
)

// RegisterUseCase is an autogenerated mock type for the RegisterUseCase type
type RegisterUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, in
func (_m *RegisterUseCase) Execute(ctx context.Context, in dto.RegisterInput) (dto.RegisterOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.RegisterOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterInput) (dto.RegisterOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterInput) dto.RegisterOutput); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.RegisterOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RegisterInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRegisterUseCase creates a new instance of RegisterUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegisterUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegisterUseCase {
	mock := &RegisterUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
