// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/maket12/ads-service/authservice/internal/app/dto"
	mock "github.com/stretchr/testify/mock"
)

// ValidateAccessTokenUseCase is an autogenerated mock type for the ValidateAccessTokenUseCase type
type ValidateAccessTokenUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, in
func (_m *ValidateAccessTokenUseCase) Execute(ctx context.Context, in dto.ValidateAccessTokenInput) (dto.ValidateAccessTokenOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.ValidateAccessTokenOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ValidateAccessTokenInput) (dto.ValidateAccessTokenOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ValidateAccessTokenInput) dto.ValidateAccessTokenOutput); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.ValidateAccessTokenOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ValidateAccessTokenInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewValidateAccessTokenUseCase creates a new instance of ValidateAccessTokenUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidateAccessTokenUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidateAccessTokenUseCase {
	mock := &ValidateAccessTokenUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
