# .mockery.yml
with-expecter: true
recursive: true
all: true

dir: "internal/domain/port/mocks"
outpkg: "mocks"


packages:
  github.com/maket12/ads-service/backend/userservice/internal/domain/port:
    config:
      all: true