// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maket12/ads-service/adservice/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAdRepository is an autogenerated mock type for the AdRepository type
type MockAdRepository struct {
	mock.Mock
}

type MockAdRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdRepository) EXPECT() *MockAdRepository_Expecter {
	return &MockAdRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, ad
func (_m *MockAdRepository) Create(ctx context.Context, ad *model.Ad) error {
	ret := _m.Called(ctx, ad)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Ad) error); ok {
		r0 = rf(ctx, ad)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAdRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ad *model.Ad
func (_e *MockAdRepository_Expecter) Create(ctx interface{}, ad interface{}) *MockAdRepository_Create_Call {
	return &MockAdRepository_Create_Call{Call: _e.mock.On("Create", ctx, ad)}
}

func (_c *MockAdRepository_Create_Call) Run(run func(ctx context.Context, ad *model.Ad)) *MockAdRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Ad))
	})
	return _c
}

func (_c *MockAdRepository_Create_Call) Return(_a0 error) *MockAdRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Ad) error) *MockAdRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAdRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAdRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAdRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAdRepository_Delete_Call {
	return &MockAdRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAdRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAdRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdRepository_Delete_Call) Return(_a0 error) *MockAdRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAdRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function with given fields: ctx, sellerID
func (_m *MockAdRepository) DeleteAll(ctx context.Context, sellerID uuid.UUID) error {
	ret := _m.Called(ctx, sellerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, sellerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdRepository_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockAdRepository_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - ctx context.Context
//   - sellerID uuid.UUID
func (_e *MockAdRepository_Expecter) DeleteAll(ctx interface{}, sellerID interface{}) *MockAdRepository_DeleteAll_Call {
	return &MockAdRepository_DeleteAll_Call{Call: _e.mock.On("DeleteAll", ctx, sellerID)}
}

func (_c *MockAdRepository_DeleteAll_Call) Run(run func(ctx context.Context, sellerID uuid.UUID)) *MockAdRepository_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdRepository_DeleteAll_Call) Return(_a0 error) *MockAdRepository_DeleteAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdRepository_DeleteAll_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAdRepository_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockAdRepository) Get(ctx context.Context, id uuid.UUID) (*model.Ad, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Ad, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Ad); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAdRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAdRepository_Expecter) Get(ctx interface{}, id interface{}) *MockAdRepository_Get_Call {
	return &MockAdRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockAdRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAdRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdRepository_Get_Call) Return(_a0 *model.Ad, _a1 error) *MockAdRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Ad, error)) *MockAdRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListAds provides a mock function with given fields: ctx, limit, offset
func (_m *MockAdRepository) ListAds(ctx context.Context, limit int, offset int) ([]*model.Ad, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAds")
	}

	var r0 []*model.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*model.Ad, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*model.Ad); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdRepository_ListAds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAds'
type MockAdRepository_ListAds_Call struct {
	*mock.Call
}

// ListAds is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockAdRepository_Expecter) ListAds(ctx interface{}, limit interface{}, offset interface{}) *MockAdRepository_ListAds_Call {
	return &MockAdRepository_ListAds_Call{Call: _e.mock.On("ListAds", ctx, limit, offset)}
}

func (_c *MockAdRepository_ListAds_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockAdRepository_ListAds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAdRepository_ListAds_Call) Return(_a0 []*model.Ad, _a1 error) *MockAdRepository_ListAds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdRepository_ListAds_Call) RunAndReturn(run func(context.Context, int, int) ([]*model.Ad, error)) *MockAdRepository_ListAds_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, ad
func (_m *MockAdRepository) Update(ctx context.Context, ad *model.Ad) error {
	ret := _m.Called(ctx, ad)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Ad) error); ok {
		r0 = rf(ctx, ad)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAdRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ad *model.Ad
func (_e *MockAdRepository_Expecter) Update(ctx interface{}, ad interface{}) *MockAdRepository_Update_Call {
	return &MockAdRepository_Update_Call{Call: _e.mock.On("Update", ctx, ad)}
}

func (_c *MockAdRepository_Update_Call) Run(run func(ctx context.Context, ad *model.Ad)) *MockAdRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Ad))
	})
	return _c
}

func (_c *MockAdRepository_Update_Call) Return(_a0 error) *MockAdRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Ad) error) *MockAdRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, ad
func (_m *MockAdRepository) UpdateStatus(ctx context.Context, ad *model.Ad) error {
	ret := _m.Called(ctx, ad)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Ad) error); ok {
		r0 = rf(ctx, ad)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockAdRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - ad *model.Ad
func (_e *MockAdRepository_Expecter) UpdateStatus(ctx interface{}, ad interface{}) *MockAdRepository_UpdateStatus_Call {
	return &MockAdRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, ad)}
}

func (_c *MockAdRepository_UpdateStatus_Call) Run(run func(ctx context.Context, ad *model.Ad)) *MockAdRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Ad))
	})
	return _c
}

func (_c *MockAdRepository_UpdateStatus_Call) Return(_a0 error) *MockAdRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, *model.Ad) error) *MockAdRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdRepository creates a new instance of MockAdRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdRepository {
	mock := &MockAdRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
