// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maket12/ads-service/backend/adservice/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAdPublisher is an autogenerated mock type for the AdPublisher type
type MockAdPublisher struct {
	mock.Mock
}

type MockAdPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdPublisher) EXPECT() *MockAdPublisher_Expecter {
	return &MockAdPublisher_Expecter{mock: &_m.Mock}
}

// PublishAdDeleted provides a mock function with given fields: ctx, adID
func (_m *MockAdPublisher) PublishAdDeleted(ctx context.Context, adID uuid.UUID) error {
	ret := _m.Called(ctx, adID)

	if len(ret) == 0 {
		panic("no return value specified for PublishAdDeleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, adID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdPublisher_PublishAdDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishAdDeleted'
type MockAdPublisher_PublishAdDeleted_Call struct {
	*mock.Call
}

// PublishAdDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - adID uuid.UUID
func (_e *MockAdPublisher_Expecter) PublishAdDeleted(ctx interface{}, adID interface{}) *MockAdPublisher_PublishAdDeleted_Call {
	return &MockAdPublisher_PublishAdDeleted_Call{Call: _e.mock.On("PublishAdDeleted", ctx, adID)}
}

func (_c *MockAdPublisher_PublishAdDeleted_Call) Run(run func(ctx context.Context, adID uuid.UUID)) *MockAdPublisher_PublishAdDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdPublisher_PublishAdDeleted_Call) Return(_a0 error) *MockAdPublisher_PublishAdDeleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdPublisher_PublishAdDeleted_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAdPublisher_PublishAdDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// PublishAdPublished provides a mock function with given fields: ctx, ad
func (_m *MockAdPublisher) PublishAdPublished(ctx context.Context, ad *model.Ad) error {
	ret := _m.Called(ctx, ad)

	if len(ret) == 0 {
		panic("no return value specified for PublishAdPublished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Ad) error); ok {
		r0 = rf(ctx, ad)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdPublisher_PublishAdPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishAdPublished'
type MockAdPublisher_PublishAdPublished_Call struct {
	*mock.Call
}

// PublishAdPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - ad *model.Ad
func (_e *MockAdPublisher_Expecter) PublishAdPublished(ctx interface{}, ad interface{}) *MockAdPublisher_PublishAdPublished_Call {
	return &MockAdPublisher_PublishAdPublished_Call{Call: _e.mock.On("PublishAdPublished", ctx, ad)}
}

func (_c *MockAdPublisher_PublishAdPublished_Call) Run(run func(ctx context.Context, ad *model.Ad)) *MockAdPublisher_PublishAdPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Ad))
	})
	return _c
}

func (_c *MockAdPublisher_PublishAdPublished_Call) Return(_a0 error) *MockAdPublisher_PublishAdPublished_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdPublisher_PublishAdPublished_Call) RunAndReturn(run func(context.Context, *model.Ad) error) *MockAdPublisher_PublishAdPublished_Call {
	_c.Call.Return(run)
	return _c
}

// PublishAdRejected provides a mock function with given fields: ctx, adID
func (_m *MockAdPublisher) PublishAdRejected(ctx context.Context, adID uuid.UUID) error {
	ret := _m.Called(ctx, adID)

	if len(ret) == 0 {
		panic("no return value specified for PublishAdRejected")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, adID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdPublisher_PublishAdRejected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishAdRejected'
type MockAdPublisher_PublishAdRejected_Call struct {
	*mock.Call
}

// PublishAdRejected is a helper method to define mock.On call
//   - ctx context.Context
//   - adID uuid.UUID
func (_e *MockAdPublisher_Expecter) PublishAdRejected(ctx interface{}, adID interface{}) *MockAdPublisher_PublishAdRejected_Call {
	return &MockAdPublisher_PublishAdRejected_Call{Call: _e.mock.On("PublishAdRejected", ctx, adID)}
}

func (_c *MockAdPublisher_PublishAdRejected_Call) Run(run func(ctx context.Context, adID uuid.UUID)) *MockAdPublisher_PublishAdRejected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdPublisher_PublishAdRejected_Call) Return(_a0 error) *MockAdPublisher_PublishAdRejected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdPublisher_PublishAdRejected_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAdPublisher_PublishAdRejected_Call {
	_c.Call.Return(run)
	return _c
}

// PublishAdUpdated provides a mock function with given fields: ctx, ad
func (_m *MockAdPublisher) PublishAdUpdated(ctx context.Context, ad *model.Ad) error {
	ret := _m.Called(ctx, ad)

	if len(ret) == 0 {
		panic("no return value specified for PublishAdUpdated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Ad) error); ok {
		r0 = rf(ctx, ad)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdPublisher_PublishAdUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishAdUpdated'
type MockAdPublisher_PublishAdUpdated_Call struct {
	*mock.Call
}

// PublishAdUpdated is a helper method to define mock.On call
//   - ctx context.Context
//   - ad *model.Ad
func (_e *MockAdPublisher_Expecter) PublishAdUpdated(ctx interface{}, ad interface{}) *MockAdPublisher_PublishAdUpdated_Call {
	return &MockAdPublisher_PublishAdUpdated_Call{Call: _e.mock.On("PublishAdUpdated", ctx, ad)}
}

func (_c *MockAdPublisher_PublishAdUpdated_Call) Run(run func(ctx context.Context, ad *model.Ad)) *MockAdPublisher_PublishAdUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Ad))
	})
	return _c
}

func (_c *MockAdPublisher_PublishAdUpdated_Call) Return(_a0 error) *MockAdPublisher_PublishAdUpdated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdPublisher_PublishAdUpdated_Call) RunAndReturn(run func(context.Context, *model.Ad) error) *MockAdPublisher_PublishAdUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdPublisher creates a new instance of MockAdPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdPublisher {
	mock := &MockAdPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
