// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMediaRepository is an autogenerated mock type for the MediaRepository type
type MockMediaRepository struct {
	mock.Mock
}

type MockMediaRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaRepository) EXPECT() *MockMediaRepository_Expecter {
	return &MockMediaRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, adID
func (_m *MockMediaRepository) Delete(ctx context.Context, adID uuid.UUID) error {
	ret := _m.Called(ctx, adID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, adID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMediaRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - adID uuid.UUID
func (_e *MockMediaRepository_Expecter) Delete(ctx interface{}, adID interface{}) *MockMediaRepository_Delete_Call {
	return &MockMediaRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, adID)}
}

func (_c *MockMediaRepository_Delete_Call) Run(run func(ctx context.Context, adID uuid.UUID)) *MockMediaRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMediaRepository_Delete_Call) Return(_a0 error) *MockMediaRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockMediaRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, adID
func (_m *MockMediaRepository) Get(ctx context.Context, adID uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, adID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return rf(ctx, adID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = rf(ctx, adID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, adID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMediaRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - adID uuid.UUID
func (_e *MockMediaRepository_Expecter) Get(ctx interface{}, adID interface{}) *MockMediaRepository_Get_Call {
	return &MockMediaRepository_Get_Call{Call: _e.mock.On("Get", ctx, adID)}
}

func (_c *MockMediaRepository_Get_Call) Run(run func(ctx context.Context, adID uuid.UUID)) *MockMediaRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMediaRepository_Get_Call) Return(_a0 []string, _a1 error) *MockMediaRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]string, error)) *MockMediaRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, adID, images
func (_m *MockMediaRepository) Save(ctx context.Context, adID uuid.UUID, images []string) error {
	ret := _m.Called(ctx, adID, images)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) error); ok {
		r0 = rf(ctx, adID, images)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMediaRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - adID uuid.UUID
//   - images []string
func (_e *MockMediaRepository_Expecter) Save(ctx interface{}, adID interface{}, images interface{}) *MockMediaRepository_Save_Call {
	return &MockMediaRepository_Save_Call{Call: _e.mock.On("Save", ctx, adID, images)}
}

func (_c *MockMediaRepository_Save_Call) Run(run func(ctx context.Context, adID uuid.UUID, images []string)) *MockMediaRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]string))
	})
	return _c
}

func (_c *MockMediaRepository_Save_Call) Return(_a0 error) *MockMediaRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_Save_Call) RunAndReturn(run func(context.Context, uuid.UUID, []string) error) *MockMediaRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaRepository creates a new instance of MockMediaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaRepository {
	mock := &MockMediaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
