// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maket12/ads-service/userservice/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProfileRepository is an autogenerated mock type for the ProfileRepository type
type MockProfileRepository struct {
	mock.Mock
}

type MockProfileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileRepository) EXPECT() *MockProfileRepository_Expecter {
	return &MockProfileRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, profile
func (_m *MockProfileRepository) Create(ctx context.Context, profile *model.Profile) error {
	ret := _m.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Profile) error); ok {
		r0 = rf(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProfileRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProfileRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - profile *model.Profile
func (_e *MockProfileRepository_Expecter) Create(ctx interface{}, profile interface{}) *MockProfileRepository_Create_Call {
	return &MockProfileRepository_Create_Call{Call: _e.mock.On("Create", ctx, profile)}
}

func (_c *MockProfileRepository_Create_Call) Run(run func(ctx context.Context, profile *model.Profile)) *MockProfileRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Profile))
	})
	return _c
}

func (_c *MockProfileRepository_Create_Call) Return(_a0 error) *MockProfileRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProfileRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Profile) error) *MockProfileRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, accountID
func (_m *MockProfileRepository) Delete(ctx context.Context, accountID uuid.UUID) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProfileRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProfileRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
func (_e *MockProfileRepository_Expecter) Delete(ctx interface{}, accountID interface{}) *MockProfileRepository_Delete_Call {
	return &MockProfileRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, accountID)}
}

func (_c *MockProfileRepository_Delete_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockProfileRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProfileRepository_Delete_Call) Return(_a0 error) *MockProfileRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProfileRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockProfileRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, accountID
func (_m *MockProfileRepository) Get(ctx context.Context, accountID uuid.UUID) (*model.Profile, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Profile, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Profile); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProfileRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProfileRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
func (_e *MockProfileRepository_Expecter) Get(ctx interface{}, accountID interface{}) *MockProfileRepository_Get_Call {
	return &MockProfileRepository_Get_Call{Call: _e.mock.On("Get", ctx, accountID)}
}

func (_c *MockProfileRepository_Get_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockProfileRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProfileRepository_Get_Call) Return(_a0 *model.Profile, _a1 error) *MockProfileRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProfileRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Profile, error)) *MockProfileRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListProfiles provides a mock function with given fields: ctx, limit, offset
func (_m *MockProfileRepository) ListProfiles(ctx context.Context, limit int, offset int) ([]*model.Profile, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListProfiles")
	}

	var r0 []*model.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*model.Profile, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*model.Profile); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProfileRepository_ListProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProfiles'
type MockProfileRepository_ListProfiles_Call struct {
	*mock.Call
}

// ListProfiles is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockProfileRepository_Expecter) ListProfiles(ctx interface{}, limit interface{}, offset interface{}) *MockProfileRepository_ListProfiles_Call {
	return &MockProfileRepository_ListProfiles_Call{Call: _e.mock.On("ListProfiles", ctx, limit, offset)}
}

func (_c *MockProfileRepository_ListProfiles_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockProfileRepository_ListProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockProfileRepository_ListProfiles_Call) Return(_a0 []*model.Profile, _a1 error) *MockProfileRepository_ListProfiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProfileRepository_ListProfiles_Call) RunAndReturn(run func(context.Context, int, int) ([]*model.Profile, error)) *MockProfileRepository_ListProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, profile
func (_m *MockProfileRepository) Update(ctx context.Context, profile *model.Profile) error {
	ret := _m.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Profile) error); ok {
		r0 = rf(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProfileRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProfileRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - profile *model.Profile
func (_e *MockProfileRepository_Expecter) Update(ctx interface{}, profile interface{}) *MockProfileRepository_Update_Call {
	return &MockProfileRepository_Update_Call{Call: _e.mock.On("Update", ctx, profile)}
}

func (_c *MockProfileRepository_Update_Call) Run(run func(ctx context.Context, profile *model.Profile)) *MockProfileRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Profile))
	})
	return _c
}

func (_c *MockProfileRepository_Update_Call) Return(_a0 error) *MockProfileRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProfileRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Profile) error) *MockProfileRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileRepository creates a new instance of MockProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileRepository {
	mock := &MockProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
