// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPhoneValidator is an autogenerated mock type for the PhoneValidator type
type MockPhoneValidator struct {
	mock.Mock
}

type MockPhoneValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPhoneValidator) EXPECT() *MockPhoneValidator_Expecter {
	return &MockPhoneValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: ctx, phone
func (_m *MockPhoneValidator) Validate(ctx context.Context, phone string) (string, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, phone)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPhoneValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockPhoneValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockPhoneValidator_Expecter) Validate(ctx interface{}, phone interface{}) *MockPhoneValidator_Validate_Call {
	return &MockPhoneValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, phone)}
}

func (_c *MockPhoneValidator_Validate_Call) Run(run func(ctx context.Context, phone string)) *MockPhoneValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPhoneValidator_Validate_Call) Return(_a0 string, _a1 error) *MockPhoneValidator_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPhoneValidator_Validate_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockPhoneValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPhoneValidator creates a new instance of MockPhoneValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPhoneValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPhoneValidator {
	mock := &MockPhoneValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
