package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"ads/gateway/graph/model"
	"ads/pkg/generated/ad_v1"
	"ads/pkg/generated/auth_v1"
	"ads/pkg/generated/user_v1"
	"ads/pkg/utils"
	"context"
	"fmt"
	"time"
)

// Price is the resolver for the price field.
func (r *adResolver) Price(ctx context.Context, obj *ad_v1.GetAdResponse) (float64, error) {
	return float64(obj.GetPrice()), nil
}

// Status is the resolver for the status field.
func (r *adResolver) Status(ctx context.Context, obj *ad_v1.GetAdResponse) (model.AdStatus, error) {
	return model.AdStatus(obj.Status), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *adResolver) CreatedAt(ctx context.Context, obj *ad_v1.GetAdResponse) (*string, error) {
	if obj.GetCreatedAt() == nil {
		return nil, nil
	}
	t := obj.GetCreatedAt().AsTime().Format(time.RFC3339)
	return &t, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *adResolver) UpdatedAt(ctx context.Context, obj *ad_v1.GetAdResponse) (*string, error) {
	if obj.GetUpdatedAt() == nil {
		return nil, nil
	}
	t := obj.GetUpdatedAt().AsTime().Format(time.RFC3339)
	return &t, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (string, error) {
	resp, err := r.AuthClient.Register(ctx, &auth_v1.RegisterRequest{
		Email:    email,
		Password: password,
	})
	if err != nil {
		return "", err
	}
	return resp.GetAccountId(), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string, ip *string, userAgent *string) (*auth_v1.LoginResponse, error) {
	resp, err := r.AuthClient.Login(ctx, &auth_v1.LoginRequest{
		Email:     email,
		Password:  password,
		Ip:        ip,
		UserAgent: userAgent,
	})
	if err != nil {
		return nil, err
	}
	return &auth_v1.LoginResponse{
		AccessToken:  resp.GetAccessToken(),
		RefreshToken: resp.GetRefreshToken(),
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken string) (bool, error) {
	resp, err := r.AuthClient.Logout(
		ctx, &auth_v1.LogoutRequest{RefreshToken: refreshToken},
	)
	if err != nil {
		return false, err
	}
	return resp.GetLogout(), nil
}

// RefreshSession is the resolver for the refreshSession field.
func (r *mutationResolver) RefreshSession(ctx context.Context, oldRefreshToken string, ip *string, userAgent *string) (*auth_v1.RefreshSessionResponse, error) {
	resp, err := r.AuthClient.RefreshSession(ctx, &auth_v1.RefreshSessionRequest{
		OldRefreshToken: oldRefreshToken,
		Ip:              ip,
		UserAgent:       userAgent,
	})
	if err != nil {
		return nil, err
	}
	return &auth_v1.RefreshSessionResponse{
		AccessToken:  resp.GetAccessToken(),
		RefreshToken: resp.GetRefreshToken(),
	}, nil
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, accountID string, role string) (bool, error) {
	resp, err := r.AuthClient.AssignRole(ctx, &auth_v1.AssignRoleRequest{
		AccountId: accountID,
		Role:      role,
	})
	if err != nil {
		return false, err
	}
	return resp.GetAssign(), nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, firstName *string, lastName *string, phone *string, avatarURL *string, bio *string) (bool, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return false, fmt.Errorf("unauthorized")
	}

	outCtx := utils.PackAccountIDForGRPC(ctx, idVal.(string))

	resp, err := r.UserClient.UpdateProfile(outCtx, &user_v1.UpdateProfileRequest{
		FirstName: firstName,
		LastName:  lastName,
		Phone:     phone,
		AvatarUrl: avatarURL,
		Bio:       bio,
	})
	if err != nil {
		return false, err
	}

	return resp.GetSuccess(), nil
}

// CreateAd is the resolver for the createAd field.
func (r *mutationResolver) CreateAd(ctx context.Context, title string, description *string, price float64, images []*string) (string, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return "", fmt.Errorf("unauthorized")
	}

	outCtx := utils.PackAccountIDForGRPC(ctx, idVal.(string))

	var imagesFixed []string
	if len(images) != 0 {
		for i := range images {
			if images[i] != nil {
				imagesFixed[i] = *images[i]
			}
		}
	}

	resp, err := r.AdClient.CreateAd(outCtx, &ad_v1.CreateAdRequest{
		Title:       title,
		Description: description,
		Price:       int64(price),
		Images:      imagesFixed,
	})
	if err != nil {
		return "", err
	}

	return resp.GetAdId(), nil
}

// UpdateAd is the resolver for the updateAd field.
func (r *mutationResolver) UpdateAd(ctx context.Context, adID string, title *string, description *string, price *float64, images []*string) (bool, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return false, fmt.Errorf("unauthorized")
	}

	outCtx := utils.PackAccountIDForGRPC(ctx, idVal.(string))

	var priceFixed int64
	if price != nil {
		priceFixed = int64(*price)
	}

	var imagesFixed []string
	if len(images) != 0 {
		for i := range images {
			if images[i] != nil {
				imagesFixed[i] = *images[i]
			}
		}
	}

	resp, err := r.AdClient.UpdateAd(outCtx, &ad_v1.UpdateAdRequest{
		AdId:        adID,
		Title:       title,
		Description: description,
		Price:       &priceFixed,
		Images:      imagesFixed,
	})
	if err != nil {
		return false, err
	}

	return resp.GetSuccess(), nil
}

// UpdateAdStatus is the resolver for the updateAdStatus field.
func (r *mutationResolver) UpdateAdStatus(ctx context.Context, adID string, adStatus model.AdStatus) (bool, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return false, fmt.Errorf("unauthorized")
	}

	outCtx := utils.PackAccountIDForGRPC(ctx, idVal.(string))

	switch adStatus {
	case model.AdStatusPublished:
		resp, err := r.AdClient.PublishAd(outCtx, &ad_v1.PublishAdRequest{AdId: adID})
		if err != nil {
			return false, err
		}
		return resp.GetSuccess(), nil

	case model.AdStatusRejected:
		resp, err := r.AdClient.RejectAd(outCtx, &ad_v1.RejectAdRequest{AdId: adID})
		if err != nil {
			return false, err
		}
		return resp.GetSuccess(), nil

	case model.AdStatusDeleted:
		resp, err := r.AdClient.DeleteAd(outCtx, &ad_v1.DeleteAdRequest{AdId: adID})
		if err != nil {
			return false, err
		}
		return resp.GetSuccess(), nil
	}

	return false, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*user_v1.GetProfileResponse, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	roleVal := ctx.Value(utils.AccountRoleKey)
	if roleVal == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	outCtx := utils.PackAccountIDForGRPC(ctx, idVal.(string))
	outCtx = utils.PackAccountRoleForGRPC(outCtx, roleVal.(string))

	return r.UserClient.GetProfile(outCtx, &user_v1.GetProfileRequest{})
}

// Ad is the resolver for the ad field.
func (r *queryResolver) Ad(ctx context.Context, adID string) (*ad_v1.GetAdResponse, error) {
	idVal := ctx.Value(utils.AccountIDKey)
	if idVal == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	outCtx := utils.PackAccountIDForGRPC(ctx, idVal.(string))

	return r.AdClient.GetAd(outCtx, &ad_v1.GetAdRequest{AdId: adID})
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *user_v1.GetProfileResponse) (string, error) {
	return obj.GetAccountId(), nil
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *user_v1.GetProfileResponse) (*string, error) {
	roleVal := ctx.Value(utils.AccountRoleKey)
	if roleVal == nil {
		return nil, nil
	}
	role := roleVal.(string)
	return &role, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *user_v1.GetProfileResponse) (*string, error) {
	if obj.GetUpdatedAt() == nil {
		return nil, nil
	}
	t := obj.GetUpdatedAt().AsTime().Format(time.RFC3339)
	return &t, nil
}

// Ad returns AdResolver implementation.
func (r *Resolver) Ad() AdResolver { return &adResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type adResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
