package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"

	ad_v1 "github.com/maket12/ads-service/adservice/pkg/generated/ad_v1"
	auth_v1 "github.com/maket12/ads-service/authservice/pkg/generated/auth_v1"
	user_v1 "github.com/maket12/ads-service/userservice/pkg/generated/user_v1"

	"github.com/maket12/ads-service/gateway/graph/generated"
	"github.com/maket12/ads-service/gateway/graph/model"
	"github.com/maket12/ads-service/gateway/internal/authctx"
)

// ---- Query ----

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	id, err := authctx.MustFromContext(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.User.GetProfile(authctx.Outgoing(ctx), &user_v1.GetProfileRequest{})
	if err != nil {
		return nil, fmt.Errorf("fetching profile: %w", err)
	}

	return &model.User{
		ID:        graphql.ID(resp.GetAccountId()),
		Role:      strPtr(id.Role),
		FirstName: optStr(resp.FirstName),
		LastName:  optStr(resp.LastName),
		Phone:     optStr(resp.Phone),
		AvatarURL: optStr(resp.AvatarUrl),
		Bio:       optStr(resp.Bio),
		UpdatedAt: timestampPtr(resp.GetUpdatedAt()),
	}, nil
}

// Ad is the resolver for the ad field.
func (r *queryResolver) Ad(ctx context.Context, adID string) (*model.Ad, error) {
	resp, err := r.Clients.Ad.GetAd(authctx.Outgoing(ctx), &ad_v1.GetAdRequest{AdId: adID})
	if err != nil {
		return nil, fmt.Errorf("fetching ad: %w", err)
	}
	return toModelAd(resp.GetAd()), nil
}

// ---- Mutation: Auth ----

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (string, error) {
	resp, err := r.Clients.Auth.Register(ctx, &auth_v1.RegisterRequest{Email: email, Password: password})
	if err != nil {
		return "", fmt.Errorf("registering account: %w", err)
	}
	return resp.GetAccountId(), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string, ip *string, userAgent *string) (*model.LoginResponse, error) {
	resp, err := r.Clients.Auth.Login(ctx, &auth_v1.LoginRequest{
		Email:     email,
		Password:  password,
		Ip:        ip,
		UserAgent: userAgent,
	})
	if err != nil {
		return nil, fmt.Errorf("logging in: %w", err)
	}
	return &model.LoginResponse{
		AccessToken:  resp.GetAccessToken(),
		RefreshToken: resp.GetRefreshToken(),
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken string) (bool, error) {
	resp, err := r.Clients.Auth.Logout(ctx, &auth_v1.LogoutRequest{RefreshToken: refreshToken})
	if err != nil {
		return false, fmt.Errorf("logging out: %w", err)
	}
	return resp.GetLogout(), nil
}

// RefreshSession is the resolver for the refreshSession field.
func (r *mutationResolver) RefreshSession(ctx context.Context, oldRefreshToken string, ip *string, userAgent *string) (*model.RefreshSessionResponse, error) {
	resp, err := r.Clients.Auth.RefreshSession(ctx, &auth_v1.RefreshSessionRequest{
		OldRefreshToken: oldRefreshToken,
		Ip:              ip,
		UserAgent:       userAgent,
	})
	if err != nil {
		return nil, fmt.Errorf("refreshing session: %w", err)
	}
	return &model.RefreshSessionResponse{
		AccessToken:  resp.GetAccessToken(),
		RefreshToken: resp.GetRefreshToken(),
	}, nil
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, accountID string, role string) (bool, error) {
	caller, err := authctx.MustFromContext(ctx)
	if err != nil {
		return false, err
	}
	// TODO: replace with your actual admin-role check once role names are
	// finalized (e.g. caller.Role != "admin").
	if caller.Role != "admin" {
		return false, authctx.ErrForbidden
	}

	resp, err := r.Clients.Auth.AssignRole(authctx.Outgoing(ctx), &auth_v1.AssignRoleRequest{
		AccountId: accountID,
		Role:      role,
	})
	if err != nil {
		return false, fmt.Errorf("assigning role: %w", err)
	}
	return resp.GetAssigned(), nil
}

// ---- Mutation: User ----

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, firstName *string, lastName *string, phone *string, avatarURL *string, bio *string) (bool, error) {
	if _, err := authctx.MustFromContext(ctx); err != nil {
		return false, err
	}

	resp, err := r.Clients.User.UpdateProfile(authctx.Outgoing(ctx), &user_v1.UpdateProfileRequest{
		FirstName: firstName,
		LastName:  lastName,
		Phone:     phone,
		AvatarUrl: avatarURL,
		Bio:       bio,
	})
	if err != nil {
		return false, fmt.Errorf("updating profile: %w", err)
	}
	return resp.GetSuccess(), nil
}

// ---- Mutation: Ad ----

// CreateAd is the resolver for the createAd field.
func (r *mutationResolver) CreateAd(ctx context.Context, title string, description *string, price float64, images []*string) (string, error) {
	if _, err := authctx.MustFromContext(ctx); err != nil {
		return "", err
	}

	resp, err := r.Clients.Ad.CreateAd(authctx.Outgoing(ctx), &ad_v1.CreateAdRequest{
		Title:       title,
		Description: description,
		Price:       int64(price),
		Images:      derefAll(images),
	})
	if err != nil {
		return "", fmt.Errorf("creating ad: %w", err)
	}
	return resp.GetAdId(), nil
}

// UpdateAd is the resolver for the updateAd field.
func (r *mutationResolver) UpdateAd(ctx context.Context, adID string, title *string, description *string, price *float64, images []*string) (bool, error) {
	if _, err := authctx.MustFromContext(ctx); err != nil {
		return false, err
	}

	var priceReq *int64
	if price != nil {
		p := int64(*price)
		priceReq = &p
	}

	resp, err := r.Clients.Ad.UpdateAd(authctx.Outgoing(ctx), &ad_v1.UpdateAdRequest{
		AdId:        adID,
		Title:       title,
		Description: description,
		Price:       priceReq,
		Images:      derefAll(images),
	})
	if err != nil {
		return false, fmt.Errorf("updating ad: %w", err)
	}
	return resp.GetSuccess(), nil
}

// UpdateAdStatus is the resolver for the updateAdStatus field.
func (r *mutationResolver) UpdateAdStatus(ctx context.Context, adID string, adStatus model.AdStatus) (bool, error) {
	if _, err := authctx.MustFromContext(ctx); err != nil {
		return false, err
	}

	octx := authctx.Outgoing(ctx)
	switch adStatus {
	case model.AdStatusPublished:
		resp, err := r.Clients.Ad.PublishAd(octx, &ad_v1.PublishAdRequest{AdId: adID})
		if err != nil {
			return false, fmt.Errorf("publishing ad: %w", err)
		}
		return resp.GetSuccess(), nil
	case model.AdStatusRejected:
		resp, err := r.Clients.Ad.RejectAd(octx, &ad_v1.RejectAdRequest{AdId: adID})
		if err != nil {
			return false, fmt.Errorf("rejecting ad: %w", err)
		}
		return resp.GetSuccess(), nil
	case model.AdStatusDeleted:
		resp, err := r.Clients.Ad.DeleteAd(octx, &ad_v1.DeleteAdRequest{AdId: adID})
		if err != nil {
			return false, fmt.Errorf("deleting ad: %w", err)
		}
		return resp.GetSuccess(), nil
	default:
		return false, fmt.Errorf("cannot transition ad to status %s", adStatus)
	}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type queryResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
