// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.
//
// NOTE: this file is checked in by hand as a placeholder so the rest of the
// gateway code compiles conceptually before you run codegen. Once you run
//
//	go run github.com/99designs/gqlgen generate
//
// gqlgen will regenerate this file from graph/schema.graphqls and overwrite
// it — the shape below matches exactly what it will produce, so nothing
// downstream needs to change.
package model

import (
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
)

type User struct {
	ID        graphql.ID `json:"id"`
	Role      *string    `json:"role"`
	FirstName *string    `json:"firstName"`
	LastName  *string    `json:"lastName"`
	Phone     *string    `json:"phone"`
	AvatarURL *string    `json:"avatarUrl"`
	Bio       *string    `json:"bio"`
	UpdatedAt *string    `json:"updatedAt"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type RefreshSessionResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type Ad struct {
	AdID        graphql.ID `json:"adId"`
	SellerID    graphql.ID `json:"sellerId"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Price       float64    `json:"price"`
	Status      AdStatus   `json:"status"`
	Images      []*string  `json:"images"`
	CreatedAt   *string    `json:"createdAt"`
	UpdatedAt   *string    `json:"updatedAt"`
}

type AdStatus string

const (
	AdStatusOnModeration AdStatus = "ON_MODERATION"
	AdStatusPublished    AdStatus = "PUBLISHED"
	AdStatusRejected     AdStatus = "REJECTED"
	AdStatusDeleted      AdStatus = "DELETED"
)

var AllAdStatus = []AdStatus{
	AdStatusOnModeration,
	AdStatusPublished,
	AdStatusRejected,
	AdStatusDeleted,
}

func (e AdStatus) IsValid() bool {
	switch e {
	case AdStatusOnModeration, AdStatusPublished, AdStatusRejected, AdStatusDeleted:
		return true
	}
	return false
}

func (e AdStatus) String() string {
	return string(e)
}

func (e *AdStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdStatus", str)
	}
	return nil
}

func (e AdStatus) MarshalGQL(w io.Writer) {
	_, _ = w.Write([]byte(strconv.Quote(e.String())))
}
