// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AccountPublisher is an autogenerated mock type for the AccountPublisher type
type AccountPublisher struct {
	mock.Mock
}

// PublishAccountCreate provides a mock function with given fields: ctx, accountID
func (_m *AccountPublisher) PublishAccountCreate(ctx context.Context, accountID uuid.UUID) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for PublishAccountCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAccountPublisher creates a new instance of AccountPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountPublisher {
	mock := &AccountPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
