// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/maket12/ads-service/authservice/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AccountRoleRepository is an autogenerated mock type for the AccountRoleRepository type
type AccountRoleRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, accountRole
func (_m *AccountRoleRepository) Create(ctx context.Context, accountRole *model.AccountRole) error {
	ret := _m.Called(ctx, accountRole)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AccountRole) error); ok {
		r0 = rf(ctx, accountRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, accountID
func (_m *AccountRoleRepository) Delete(ctx context.Context, accountID uuid.UUID) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, accountID
func (_m *AccountRoleRepository) Get(ctx context.Context, accountID uuid.UUID) (*model.AccountRole, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.AccountRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.AccountRole, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.AccountRole); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccountRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, accountRole
func (_m *AccountRoleRepository) Update(ctx context.Context, accountRole *model.AccountRole) error {
	ret := _m.Called(ctx, accountRole)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AccountRole) error); ok {
		r0 = rf(ctx, accountRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAccountRoleRepository creates a new instance of AccountRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRoleRepository {
	mock := &AccountRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
