// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/maket12/ads-service/authservice/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// RefreshSessionRepository is an autogenerated mock type for the RefreshSessionRepository type
type RefreshSessionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, session
func (_m *RefreshSessionRepository) Create(ctx context.Context, session *model.RefreshSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RefreshSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteExpired provides a mock function with given fields: ctx, expiresAt
func (_m *RefreshSessionRepository) DeleteExpired(ctx context.Context, expiresAt time.Time) error {
	ret := _m.Called(ctx, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = rf(ctx, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByHash provides a mock function with given fields: ctx, tokenHash
func (_m *RefreshSessionRepository) GetByHash(ctx context.Context, tokenHash string) (*model.RefreshSession, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *model.RefreshSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.RefreshSession, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.RefreshSession); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RefreshSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, tokenID
func (_m *RefreshSessionRepository) GetByID(ctx context.Context, tokenID uuid.UUID) (*model.RefreshSession, error) {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.RefreshSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.RefreshSession, error)); ok {
		return rf(ctx, tokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.RefreshSession); ok {
		r0 = rf(ctx, tokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RefreshSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListActiveForAccount provides a mock function with given fields: ctx, accountID
func (_m *RefreshSessionRepository) ListActiveForAccount(ctx context.Context, accountID uuid.UUID) ([]*model.RefreshSession, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveForAccount")
	}

	var r0 []*model.RefreshSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.RefreshSession, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.RefreshSession); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RefreshSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Revoke provides a mock function with given fields: ctx, session
func (_m *RefreshSessionRepository) Revoke(ctx context.Context, session *model.RefreshSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RefreshSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeAllForAccount provides a mock function with given fields: ctx, accountID, reason
func (_m *RefreshSessionRepository) RevokeAllForAccount(ctx context.Context, accountID uuid.UUID, reason *string) error {
	ret := _m.Called(ctx, accountID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string) error); ok {
		r0 = rf(ctx, accountID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeDescendants provides a mock function with given fields: ctx, sessionID, reason
func (_m *RefreshSessionRepository) RevokeDescendants(ctx context.Context, sessionID uuid.UUID, reason *string) error {
	ret := _m.Called(ctx, sessionID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RevokeDescendants")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string) error); ok {
		r0 = rf(ctx, sessionID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRefreshSessionRepository creates a new instance of RefreshSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshSessionRepository {
	mock := &RefreshSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
