// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAccountPublisher is an autogenerated mock type for the AccountPublisher type
type MockAccountPublisher struct {
	mock.Mock
}

type MockAccountPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountPublisher) EXPECT() *MockAccountPublisher_Expecter {
	return &MockAccountPublisher_Expecter{mock: &_m.Mock}
}

// PublishAccountCreate provides a mock function with given fields: ctx, accountID
func (_m *MockAccountPublisher) PublishAccountCreate(ctx context.Context, accountID uuid.UUID) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for PublishAccountCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountPublisher_PublishAccountCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishAccountCreate'
type MockAccountPublisher_PublishAccountCreate_Call struct {
	*mock.Call
}

// PublishAccountCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
func (_e *MockAccountPublisher_Expecter) PublishAccountCreate(ctx interface{}, accountID interface{}) *MockAccountPublisher_PublishAccountCreate_Call {
	return &MockAccountPublisher_PublishAccountCreate_Call{Call: _e.mock.On("PublishAccountCreate", ctx, accountID)}
}

func (_c *MockAccountPublisher_PublishAccountCreate_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockAccountPublisher_PublishAccountCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAccountPublisher_PublishAccountCreate_Call) Return(_a0 error) *MockAccountPublisher_PublishAccountCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountPublisher_PublishAccountCreate_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAccountPublisher_PublishAccountCreate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountPublisher creates a new instance of MockAccountPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountPublisher {
	mock := &MockAccountPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
