// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maket12/ads-service/authservice/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAccountRoleRepository is an autogenerated mock type for the AccountRoleRepository type
type MockAccountRoleRepository struct {
	mock.Mock
}

type MockAccountRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRoleRepository) EXPECT() *MockAccountRoleRepository_Expecter {
	return &MockAccountRoleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, accountRole
func (_m *MockAccountRoleRepository) Create(ctx context.Context, accountRole *model.AccountRole) error {
	ret := _m.Called(ctx, accountRole)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AccountRole) error); ok {
		r0 = rf(ctx, accountRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - accountRole *model.AccountRole
func (_e *MockAccountRoleRepository_Expecter) Create(ctx interface{}, accountRole interface{}) *MockAccountRoleRepository_Create_Call {
	return &MockAccountRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, accountRole)}
}

func (_c *MockAccountRoleRepository_Create_Call) Run(run func(ctx context.Context, accountRole *model.AccountRole)) *MockAccountRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.AccountRole))
	})
	return _c
}

func (_c *MockAccountRoleRepository_Create_Call) Return(_a0 error) *MockAccountRoleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRoleRepository_Create_Call) RunAndReturn(run func(context.Context, *model.AccountRole) error) *MockAccountRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, accountID
func (_m *MockAccountRoleRepository) Delete(ctx context.Context, accountID uuid.UUID) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRoleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAccountRoleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
func (_e *MockAccountRoleRepository_Expecter) Delete(ctx interface{}, accountID interface{}) *MockAccountRoleRepository_Delete_Call {
	return &MockAccountRoleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, accountID)}
}

func (_c *MockAccountRoleRepository_Delete_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockAccountRoleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAccountRoleRepository_Delete_Call) Return(_a0 error) *MockAccountRoleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRoleRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAccountRoleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, accountID
func (_m *MockAccountRoleRepository) Get(ctx context.Context, accountID uuid.UUID) (*model.AccountRole, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.AccountRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.AccountRole, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.AccountRole); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccountRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRoleRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAccountRoleRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
func (_e *MockAccountRoleRepository_Expecter) Get(ctx interface{}, accountID interface{}) *MockAccountRoleRepository_Get_Call {
	return &MockAccountRoleRepository_Get_Call{Call: _e.mock.On("Get", ctx, accountID)}
}

func (_c *MockAccountRoleRepository_Get_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockAccountRoleRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAccountRoleRepository_Get_Call) Return(_a0 *model.AccountRole, _a1 error) *MockAccountRoleRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRoleRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.AccountRole, error)) *MockAccountRoleRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, accountRole
func (_m *MockAccountRoleRepository) Update(ctx context.Context, accountRole *model.AccountRole) error {
	ret := _m.Called(ctx, accountRole)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AccountRole) error); ok {
		r0 = rf(ctx, accountRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRoleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountRoleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - accountRole *model.AccountRole
func (_e *MockAccountRoleRepository_Expecter) Update(ctx interface{}, accountRole interface{}) *MockAccountRoleRepository_Update_Call {
	return &MockAccountRoleRepository_Update_Call{Call: _e.mock.On("Update", ctx, accountRole)}
}

func (_c *MockAccountRoleRepository_Update_Call) Run(run func(ctx context.Context, accountRole *model.AccountRole)) *MockAccountRoleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.AccountRole))
	})
	return _c
}

func (_c *MockAccountRoleRepository_Update_Call) Return(_a0 error) *MockAccountRoleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRoleRepository_Update_Call) RunAndReturn(run func(context.Context, *model.AccountRole) error) *MockAccountRoleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountRoleRepository creates a new instance of MockAccountRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRoleRepository {
	mock := &MockAccountRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
