// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maket12/ads-service/authservice/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockRefreshSessionRepository is an autogenerated mock type for the RefreshSessionRepository type
type MockRefreshSessionRepository struct {
	mock.Mock
}

type MockRefreshSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshSessionRepository) EXPECT() *MockRefreshSessionRepository_Expecter {
	return &MockRefreshSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session
func (_m *MockRefreshSessionRepository) Create(ctx context.Context, session *model.RefreshSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RefreshSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *model.RefreshSession
func (_e *MockRefreshSessionRepository_Expecter) Create(ctx interface{}, session interface{}) *MockRefreshSessionRepository_Create_Call {
	return &MockRefreshSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockRefreshSessionRepository_Create_Call) Run(run func(ctx context.Context, session *model.RefreshSession)) *MockRefreshSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.RefreshSession))
	})
	return _c
}

func (_c *MockRefreshSessionRepository_Create_Call) Return(_a0 error) *MockRefreshSessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshSessionRepository_Create_Call) RunAndReturn(run func(context.Context, *model.RefreshSession) error) *MockRefreshSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with given fields: ctx, expiresAt
func (_m *MockRefreshSessionRepository) DeleteExpired(ctx context.Context, expiresAt time.Time) error {
	ret := _m.Called(ctx, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = rf(ctx, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshSessionRepository_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type MockRefreshSessionRepository_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - expiresAt time.Time
func (_e *MockRefreshSessionRepository_Expecter) DeleteExpired(ctx interface{}, expiresAt interface{}) *MockRefreshSessionRepository_DeleteExpired_Call {
	return &MockRefreshSessionRepository_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx, expiresAt)}
}

func (_c *MockRefreshSessionRepository_DeleteExpired_Call) Run(run func(ctx context.Context, expiresAt time.Time)) *MockRefreshSessionRepository_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockRefreshSessionRepository_DeleteExpired_Call) Return(_a0 error) *MockRefreshSessionRepository_DeleteExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshSessionRepository_DeleteExpired_Call) RunAndReturn(run func(context.Context, time.Time) error) *MockRefreshSessionRepository_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockRefreshSessionRepository) GetByHash(ctx context.Context, tokenHash string) (*model.RefreshSession, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *model.RefreshSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.RefreshSession, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.RefreshSession); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RefreshSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshSessionRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockRefreshSessionRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRefreshSessionRepository_Expecter) GetByHash(ctx interface{}, tokenHash interface{}) *MockRefreshSessionRepository_GetByHash_Call {
	return &MockRefreshSessionRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, tokenHash)}
}

func (_c *MockRefreshSessionRepository_GetByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRefreshSessionRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshSessionRepository_GetByHash_Call) Return(_a0 *model.RefreshSession, _a1 error) *MockRefreshSessionRepository_GetByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshSessionRepository_GetByHash_Call) RunAndReturn(run func(context.Context, string) (*model.RefreshSession, error)) *MockRefreshSessionRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, tokenID
func (_m *MockRefreshSessionRepository) GetByID(ctx context.Context, tokenID uuid.UUID) (*model.RefreshSession, error) {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.RefreshSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.RefreshSession, error)); ok {
		return rf(ctx, tokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.RefreshSession); ok {
		r0 = rf(ctx, tokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RefreshSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshSessionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRefreshSessionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID uuid.UUID
func (_e *MockRefreshSessionRepository_Expecter) GetByID(ctx interface{}, tokenID interface{}) *MockRefreshSessionRepository_GetByID_Call {
	return &MockRefreshSessionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, tokenID)}
}

func (_c *MockRefreshSessionRepository_GetByID_Call) Run(run func(ctx context.Context, tokenID uuid.UUID)) *MockRefreshSessionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRefreshSessionRepository_GetByID_Call) Return(_a0 *model.RefreshSession, _a1 error) *MockRefreshSessionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshSessionRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.RefreshSession, error)) *MockRefreshSessionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveForAccount provides a mock function with given fields: ctx, accountID
func (_m *MockRefreshSessionRepository) ListActiveForAccount(ctx context.Context, accountID uuid.UUID) ([]*model.RefreshSession, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveForAccount")
	}

	var r0 []*model.RefreshSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.RefreshSession, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.RefreshSession); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RefreshSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshSessionRepository_ListActiveForAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveForAccount'
type MockRefreshSessionRepository_ListActiveForAccount_Call struct {
	*mock.Call
}

// ListActiveForAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
func (_e *MockRefreshSessionRepository_Expecter) ListActiveForAccount(ctx interface{}, accountID interface{}) *MockRefreshSessionRepository_ListActiveForAccount_Call {
	return &MockRefreshSessionRepository_ListActiveForAccount_Call{Call: _e.mock.On("ListActiveForAccount", ctx, accountID)}
}

func (_c *MockRefreshSessionRepository_ListActiveForAccount_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockRefreshSessionRepository_ListActiveForAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRefreshSessionRepository_ListActiveForAccount_Call) Return(_a0 []*model.RefreshSession, _a1 error) *MockRefreshSessionRepository_ListActiveForAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshSessionRepository_ListActiveForAccount_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.RefreshSession, error)) *MockRefreshSessionRepository_ListActiveForAccount_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForAccount provides a mock function with given fields: ctx, accountID, reason
func (_m *MockRefreshSessionRepository) RevokeAllForAccount(ctx context.Context, accountID uuid.UUID, reason *string) error {
	ret := _m.Called(ctx, accountID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string) error); ok {
		r0 = rf(ctx, accountID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshSessionRepository_RevokeAllForAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForAccount'
type MockRefreshSessionRepository_RevokeAllForAccount_Call struct {
	*mock.Call
}

// RevokeAllForAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
//   - reason *string
func (_e *MockRefreshSessionRepository_Expecter) RevokeAllForAccount(ctx interface{}, accountID interface{}, reason interface{}) *MockRefreshSessionRepository_RevokeAllForAccount_Call {
	return &MockRefreshSessionRepository_RevokeAllForAccount_Call{Call: _e.mock.On("RevokeAllForAccount", ctx, accountID, reason)}
}

func (_c *MockRefreshSessionRepository_RevokeAllForAccount_Call) Run(run func(ctx context.Context, accountID uuid.UUID, reason *string)) *MockRefreshSessionRepository_RevokeAllForAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*string))
	})
	return _c
}

func (_c *MockRefreshSessionRepository_RevokeAllForAccount_Call) Return(_a0 error) *MockRefreshSessionRepository_RevokeAllForAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshSessionRepository_RevokeAllForAccount_Call) RunAndReturn(run func(context.Context, uuid.UUID, *string) error) *MockRefreshSessionRepository_RevokeAllForAccount_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForAccountByIPUA provides a mock function with given fields: ctx, accID, ip, userAgent, reason
func (_m *MockRefreshSessionRepository) RevokeAllForAccountByIPUA(ctx context.Context, accID uuid.UUID, ip *string, userAgent *string, reason *string) error {
	ret := _m.Called(ctx, accID, ip, userAgent, reason)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForAccountByIPUA")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string, *string) error); ok {
		r0 = rf(ctx, accID, ip, userAgent, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshSessionRepository_RevokeAllForAccountByIPUA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForAccountByIPUA'
type MockRefreshSessionRepository_RevokeAllForAccountByIPUA_Call struct {
	*mock.Call
}

// RevokeAllForAccountByIPUA is a helper method to define mock.On call
//   - ctx context.Context
//   - accID uuid.UUID
//   - ip *string
//   - userAgent *string
//   - reason *string
func (_e *MockRefreshSessionRepository_Expecter) RevokeAllForAccountByIPUA(ctx interface{}, accID interface{}, ip interface{}, userAgent interface{}, reason interface{}) *MockRefreshSessionRepository_RevokeAllForAccountByIPUA_Call {
	return &MockRefreshSessionRepository_RevokeAllForAccountByIPUA_Call{Call: _e.mock.On("RevokeAllForAccountByIPUA", ctx, accID, ip, userAgent, reason)}
}

func (_c *MockRefreshSessionRepository_RevokeAllForAccountByIPUA_Call) Run(run func(ctx context.Context, accID uuid.UUID, ip *string, userAgent *string, reason *string)) *MockRefreshSessionRepository_RevokeAllForAccountByIPUA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*string), args[3].(*string), args[4].(*string))
	})
	return _c
}

func (_c *MockRefreshSessionRepository_RevokeAllForAccountByIPUA_Call) Return(_a0 error) *MockRefreshSessionRepository_RevokeAllForAccountByIPUA_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshSessionRepository_RevokeAllForAccountByIPUA_Call) RunAndReturn(run func(context.Context, uuid.UUID, *string, *string, *string) error) *MockRefreshSessionRepository_RevokeAllForAccountByIPUA_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeDescendants provides a mock function with given fields: ctx, sessionID, reason
func (_m *MockRefreshSessionRepository) RevokeDescendants(ctx context.Context, sessionID uuid.UUID, reason *string) error {
	ret := _m.Called(ctx, sessionID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RevokeDescendants")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string) error); ok {
		r0 = rf(ctx, sessionID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshSessionRepository_RevokeDescendants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeDescendants'
type MockRefreshSessionRepository_RevokeDescendants_Call struct {
	*mock.Call
}

// RevokeDescendants is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - reason *string
func (_e *MockRefreshSessionRepository_Expecter) RevokeDescendants(ctx interface{}, sessionID interface{}, reason interface{}) *MockRefreshSessionRepository_RevokeDescendants_Call {
	return &MockRefreshSessionRepository_RevokeDescendants_Call{Call: _e.mock.On("RevokeDescendants", ctx, sessionID, reason)}
}

func (_c *MockRefreshSessionRepository_RevokeDescendants_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, reason *string)) *MockRefreshSessionRepository_RevokeDescendants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*string))
	})
	return _c
}

func (_c *MockRefreshSessionRepository_RevokeDescendants_Call) Return(_a0 error) *MockRefreshSessionRepository_RevokeDescendants_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshSessionRepository_RevokeDescendants_Call) RunAndReturn(run func(context.Context, uuid.UUID, *string) error) *MockRefreshSessionRepository_RevokeDescendants_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, session
func (_m *MockRefreshSessionRepository) Update(ctx context.Context, session *model.RefreshSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RefreshSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshSessionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRefreshSessionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - session *model.RefreshSession
func (_e *MockRefreshSessionRepository_Expecter) Update(ctx interface{}, session interface{}) *MockRefreshSessionRepository_Update_Call {
	return &MockRefreshSessionRepository_Update_Call{Call: _e.mock.On("Update", ctx, session)}
}

func (_c *MockRefreshSessionRepository_Update_Call) Run(run func(ctx context.Context, session *model.RefreshSession)) *MockRefreshSessionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.RefreshSession))
	})
	return _c
}

func (_c *MockRefreshSessionRepository_Update_Call) Return(_a0 error) *MockRefreshSessionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshSessionRepository_Update_Call) RunAndReturn(run func(context.Context, *model.RefreshSession) error) *MockRefreshSessionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshSessionRepository creates a new instance of MockRefreshSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshSessionRepository {
	mock := &MockRefreshSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
