// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maket12/ads-service/authservice/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockVerificationTokenRepository is an autogenerated mock type for the VerificationTokenRepository type
type MockVerificationTokenRepository struct {
	mock.Mock
}

type MockVerificationTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerificationTokenRepository) EXPECT() *MockVerificationTokenRepository_Expecter {
	return &MockVerificationTokenRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, token
func (_m *MockVerificationTokenRepository) Delete(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVerificationTokenRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVerificationTokenRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockVerificationTokenRepository_Expecter) Delete(ctx interface{}, token interface{}) *MockVerificationTokenRepository_Delete_Call {
	return &MockVerificationTokenRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, token)}
}

func (_c *MockVerificationTokenRepository_Delete_Call) Run(run func(ctx context.Context, token string)) *MockVerificationTokenRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVerificationTokenRepository_Delete_Call) Return(_a0 error) *MockVerificationTokenRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVerificationTokenRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockVerificationTokenRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, token
func (_m *MockVerificationTokenRepository) Get(ctx context.Context, token string) (*model.VerificationToken, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.VerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.VerificationToken, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.VerificationToken); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.VerificationToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVerificationTokenRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockVerificationTokenRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockVerificationTokenRepository_Expecter) Get(ctx interface{}, token interface{}) *MockVerificationTokenRepository_Get_Call {
	return &MockVerificationTokenRepository_Get_Call{Call: _e.mock.On("Get", ctx, token)}
}

func (_c *MockVerificationTokenRepository_Get_Call) Run(run func(ctx context.Context, token string)) *MockVerificationTokenRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVerificationTokenRepository_Get_Call) Return(_a0 *model.VerificationToken, _a1 error) *MockVerificationTokenRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVerificationTokenRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*model.VerificationToken, error)) *MockVerificationTokenRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, token
func (_m *MockVerificationTokenRepository) Save(ctx context.Context, token *model.VerificationToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.VerificationToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVerificationTokenRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockVerificationTokenRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - token *model.VerificationToken
func (_e *MockVerificationTokenRepository_Expecter) Save(ctx interface{}, token interface{}) *MockVerificationTokenRepository_Save_Call {
	return &MockVerificationTokenRepository_Save_Call{Call: _e.mock.On("Save", ctx, token)}
}

func (_c *MockVerificationTokenRepository_Save_Call) Run(run func(ctx context.Context, token *model.VerificationToken)) *MockVerificationTokenRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.VerificationToken))
	})
	return _c
}

func (_c *MockVerificationTokenRepository_Save_Call) Return(_a0 error) *MockVerificationTokenRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVerificationTokenRepository_Save_Call) RunAndReturn(run func(context.Context, *model.VerificationToken) error) *MockVerificationTokenRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerificationTokenRepository creates a new instance of MockVerificationTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerificationTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerificationTokenRepository {
	mock := &MockVerificationTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
