// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	port "github.com/maket12/ads-service/authservice/internal/domain/port"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTokenGenerator is an autogenerated mock type for the TokenGenerator type
type MockTokenGenerator struct {
	mock.Mock
}

type MockTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGenerator) EXPECT() *MockTokenGenerator_Expecter {
	return &MockTokenGenerator_Expecter{mock: &_m.Mock}
}

// GeneratePair provides a mock function with given fields: ctx, accountID, role, sessionID
func (_m *MockTokenGenerator) GeneratePair(ctx context.Context, accountID uuid.UUID, role string, sessionID uuid.UUID) (*port.TokensPair, error) {
	ret := _m.Called(ctx, accountID, role, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePair")
	}

	var r0 *port.TokensPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) (*port.TokensPair, error)); ok {
		return rf(ctx, accountID, role, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) *port.TokensPair); ok {
		r0 = rf(ctx, accountID, role, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.TokensPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = rf(ctx, accountID, role, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenGenerator_GeneratePair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePair'
type MockTokenGenerator_GeneratePair_Call struct {
	*mock.Call
}

// GeneratePair is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
//   - role string
//   - sessionID uuid.UUID
func (_e *MockTokenGenerator_Expecter) GeneratePair(ctx interface{}, accountID interface{}, role interface{}, sessionID interface{}) *MockTokenGenerator_GeneratePair_Call {
	return &MockTokenGenerator_GeneratePair_Call{Call: _e.mock.On("GeneratePair", ctx, accountID, role, sessionID)}
}

func (_c *MockTokenGenerator_GeneratePair_Call) Run(run func(ctx context.Context, accountID uuid.UUID, role string, sessionID uuid.UUID)) *MockTokenGenerator_GeneratePair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockTokenGenerator_GeneratePair_Call) Return(_a0 *port.TokensPair, _a1 error) *MockTokenGenerator_GeneratePair_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenGenerator_GeneratePair_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID) (*port.TokensPair, error)) *MockTokenGenerator_GeneratePair_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: ctx, token
func (_m *MockTokenGenerator) ValidateAccessToken(ctx context.Context, token string) (uuid.UUID, string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 uuid.UUID
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenGenerator_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockTokenGenerator_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenGenerator_Expecter) ValidateAccessToken(ctx interface{}, token interface{}) *MockTokenGenerator_ValidateAccessToken_Call {
	return &MockTokenGenerator_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, token)}
}

func (_c *MockTokenGenerator_ValidateAccessToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenGenerator_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenGenerator_ValidateAccessToken_Call) Return(accountID uuid.UUID, role string, err error) *MockTokenGenerator_ValidateAccessToken_Call {
	_c.Call.Return(accountID, role, err)
	return _c
}

func (_c *MockTokenGenerator_ValidateAccessToken_Call) RunAndReturn(run func(context.Context, string) (uuid.UUID, string, error)) *MockTokenGenerator_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function with given fields: ctx, token
func (_m *MockTokenGenerator) ValidateRefreshToken(ctx context.Context, token string) (uuid.UUID, uuid.UUID, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 uuid.UUID
	var r1 uuid.UUID
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, uuid.UUID, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) uuid.UUID); ok {
		r1 = rf(ctx, token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenGenerator_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockTokenGenerator_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenGenerator_Expecter) ValidateRefreshToken(ctx interface{}, token interface{}) *MockTokenGenerator_ValidateRefreshToken_Call {
	return &MockTokenGenerator_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", ctx, token)}
}

func (_c *MockTokenGenerator_ValidateRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenGenerator_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenGenerator_ValidateRefreshToken_Call) Return(accountID uuid.UUID, sessionID uuid.UUID, err error) *MockTokenGenerator_ValidateRefreshToken_Call {
	_c.Call.Return(accountID, sessionID, err)
	return _c
}

func (_c *MockTokenGenerator_ValidateRefreshToken_Call) RunAndReturn(run func(context.Context, string) (uuid.UUID, uuid.UUID, error)) *MockTokenGenerator_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenGenerator creates a new instance of MockTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGenerator {
	mock := &MockTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
