// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEmailSender is an autogenerated mock type for the EmailSender type
type MockEmailSender struct {
	mock.Mock
}

type MockEmailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailSender) EXPECT() *MockEmailSender_Expecter {
	return &MockEmailSender_Expecter{mock: &_m.Mock}
}

// SendVerificationEmail provides a mock function with given fields: ctx, toEmail, token
func (_m *MockEmailSender) SendVerificationEmail(ctx context.Context, toEmail string, token string) error {
	ret := _m.Called(ctx, toEmail, token)

	if len(ret) == 0 {
		panic("no return value specified for SendVerificationEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, toEmail, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailSender_SendVerificationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerificationEmail'
type MockEmailSender_SendVerificationEmail_Call struct {
	*mock.Call
}

// SendVerificationEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - toEmail string
//   - token string
func (_e *MockEmailSender_Expecter) SendVerificationEmail(ctx interface{}, toEmail interface{}, token interface{}) *MockEmailSender_SendVerificationEmail_Call {
	return &MockEmailSender_SendVerificationEmail_Call{Call: _e.mock.On("SendVerificationEmail", ctx, toEmail, token)}
}

func (_c *MockEmailSender_SendVerificationEmail_Call) Run(run func(ctx context.Context, toEmail string, token string)) *MockEmailSender_SendVerificationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockEmailSender_SendVerificationEmail_Call) Return(_a0 error) *MockEmailSender_SendVerificationEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailSender_SendVerificationEmail_Call) RunAndReturn(run func(context.Context, string, string) error) *MockEmailSender_SendVerificationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailSender creates a new instance of MockEmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailSender {
	mock := &MockEmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
